name: Build SSH Server

on:
  push:
    branches:
      - main  # 在主分支推送时触发编译
  pull_request:
    branches:
      - main  # 在主分支的拉取请求时触发编译

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的 runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用最新的 checkout 版本

    - name: Set up Android NDK
      uses: android-actions/setup-ndk@v1  # 使用官方 NDK 设置动作
      with:
        version: '25.2.9519680'  # 请确保使用您本地的 NDK 版本

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install libssh dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssh-dev  # 安装 libssh 库

    - name: Configure CMake for Android arm64-v8a
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: |
        cmake --build build --target ssh_server

    - name: Upload the build artifact
      uses: actions/upload-artifact@v3  # 使用最新版本的 upload-artifact
      with:
        name: ssh_server
        path: build/ssh_server