name: Build SSH Server

on:
  push:
    branches:
      - main  # 在主分支推送时触发编译
  pull_request:
    branches:
      - main  # 在主分支的拉取请求时触发编译

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的 runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用最新的 checkout 版本

    - name: Set up Android NDK
      run: |
        # 设置 NDK 版本
        export NDK_VERSION=r23b  # 更新为有效版本
        export ANDROID_NDK_HOME=$HOME/android-ndk
        mkdir -p $ANDROID_NDK_HOME
        wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip
        unzip android-ndk-$NDK_VERSION-linux.zip -d $ANDROID_NDK_HOME
        export PATH=$ANDROID_NDK_HOME/android-ndk-$NDK_VERSION:$PATH
        echo "NDK version $NDK_VERSION is set up"

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install libssh dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssh-dev  # 安装 libssh 库

    - name: Configure CMake for Android arm64-v8a
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/android-ndk-$NDK_VERSION/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: |
        cmake --build build --target ssh_server

    - name: Upload the build artifact
      uses: actions/upload-artifact@v3  # 使用最新版本的 upload-artifact
      with:
        name: ssh_server
        path: build/ssh_server
